package com.xfxmcy.spouseWx.wsdl.photo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2015-06-16T09:03:07.353+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "PhotoWServiceService", 
                  wsdlLocation = "http://xfxmcy.com/cyws/photoWs?wsdl",
                  targetNamespace = "http://webservice.spouse.xfxmcy.com/") 
public class PhotoWServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.spouse.xfxmcy.com/", "PhotoWServiceService");
    public final static QName PhotoWServicePort = new QName("http://webservice.spouse.xfxmcy.com/", "PhotoWServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://xfxmcy.com/cyws/photoWs?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PhotoWServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://xfxmcy.com/cyws/photoWs?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PhotoWServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PhotoWServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhotoWServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PhotoWService
     */
    @WebEndpoint(name = "PhotoWServicePort")
    public PhotoWService getPhotoWServicePort() {
        return super.getPort(PhotoWServicePort, PhotoWService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhotoWService
     */
    @WebEndpoint(name = "PhotoWServicePort")
    public PhotoWService getPhotoWServicePort(WebServiceFeature... features) {
        return super.getPort(PhotoWServicePort, PhotoWService.class, features);
    }

}
